### ISSUE TITLE
Horizontal position adjustment ignores the right margin in PDF

### ISSUE THREAD

**Issue by Brunox13** [hughjonesd/huxtable#122] opened 2019-12-14 16:22 UTC
This issue arose in the following StackOverflow question: [How can you center a huxtable?](https://stackoverflow.com/questions/59240850/how-can-you-center-a-huxtable)

As described in the selected answer for the question above, there seems to be an issue with how `huxtable` proccesses (or doesn't) the right page margin. Below, I am showing different options for alignment (`"left"`, `"right"`, and `"center"`, respectively); besides the `R code` depicted in the images, each of the following markdown files used to create these PDFs start with the same code (minus the "()"):

```r
---
title: "Example"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE)
```()
```

### Left Aligned
![left-aligned](https://i.stack.imgur.com/vqiMt.png)

### Right Aligned
![right-aligned](https://i.stack.imgur.com/5y4vj.png)

### Centered
![centered](https://i.stack.imgur.com/XSfeW.png)

While the left-aligned table is positioned as expected, the right-aligned one is touching the edge of the page. In the centered table, you can see that the table is essentially centered if the right margin is ignored. **This makes me think that this issue is caused by `huxtable` somehow ignoring the right margin.**

Note that setting margins using `geometry:` in the LaTeX header does not resolve this issue either.

**Comment by hughjonesd** [comment] 2019-12-14 18:34
Hi, thanks for this issue. My feeling is that this isn't correct. Take a look at latex.R in the source. You'll see that `"center"` just uses the latex `\centering` command. The problem is that the latex version uses tabularx which expects a given width. The default width is `0.5\textwidth`. If that is wrong i.e. if your table overspills, then the centering will be wrong too. See `?position` and `?"huxtable-FAQ"` for the details.

Really, the whole latex code needs a rewrite from a proper expert. But beware: it is a hairy project to do a truly flexible table in TeX.

**Comment by Brunox13** [comment] 2019-12-14 20:34
Both `?position` and `?"huxtable-FAQ"` (and, similarly, you in the [previous issue](https://github.com/hughjonesd/huxtable/issues/6) and in your [StackOverflow comment](https://stackoverflow.com/questions/59240850/how-can-you-center-a-huxtable/59315457?noredirect=1#comment104873889_59315457)) suggest to

> Try adjusting `width(ht)`.

However, setting that to pretty much any value does not help in case of this table. So are you suggesting that that's not a problem of `huxtable` but rather of latex itself?

**Comment by hughjonesd** [comment] 2019-12-15 00:15
Hmm, if you're right that is interesting. So then we have two problems :-).

I wouldn't say it's a problem of either hux or TeX on its own. It's how they interact. tabularx is probably not the optimal table package because it demands that you set the width right - and there's no way to do that automatically. tabu might be a better option, but I'm not sure it's supported. A more radical approach would be to drop the ability to do all the things huxtable aims to do (arbitrary per-cell borders, colours, colspan etc.) and just focus on producing simple TeX code for a few key use cases. But that would be a new package....

**Comment by hughjonesd** [comment] 2019-12-15 00:16
Could you actually put the full code to reproduce here? Thanks.

**Comment by Brunox13** [comment] 2019-12-15 00:49
This is the full code that I have saved in an .Rmd file:

> \---
> title: "Example"
> output: pdf_document
> \---
> 
> \```{r setup, include=FALSE}
> knitr::opts_chunk$set(echo = TRUE, message = FALSE)
> \```
> 
> \```{r}
> iris_lm <- lm(Sepal.Width ~ ., data = iris)
> 
> ht <- huxtable::huxreg(iris_lm, iris_lm, iris_lm, iris_lm)
> 
> huxtable::position(ht) <- "center"
> 
> huxtable::width(ht) <- 0.7     # This can be varied
> 
> ht
> \```

Then I just knit to PDF.

**Comment by hughjonesd** [comment] 2020-05-02 08:21
Could you try github master? I've just committed some changes to LaTeX. In particular, try with width set and unset; and wrap TRUE and FALSE. There may be new issues, in which case feel free to open them....

**Comment by hughjonesd** [comment] 2020-05-02 08:27
The particular "right margin" issue mentioned here now seems to occur only if width is (wrongly) set. This might happen a lot though. One solution may be to set wrap = TRUE by default.

**Comment by hughjonesd** [comment] 2020-05-05 07:17
Hopefully closed by recent changes.

**Closed by hughjonesd** 2020-05-05 07:17 UTC
