### ISSUE TITLE
background hides borders in pdf latex

### ISSUE THREAD

**Issue by blset** [hughjonesd/huxtable#251] opened 2023-12-14 12:05 UTC
```
jams |> 
  insert_row(c("other", 12)) |>
  merge_cells(1, 1:2)|>
  set_background_color(row = 1, col=2, value = "cornsilk1") |>
  set_background_color(row = 3, col=2, value = "cornsilk1") |>
  set_top_border(value = brdr(1), row = 1)|>
  set_top_border(value = brdr(.2), row = 2:3)|>
  set_bottom_border(value = brdr(.2), row = 1:3)|>
  set_bottom_border(value = brdr(1), row = final(1)) 

```
once compiled with latex gives this

![Capture d’écran du 2023-12-14 12-56-37](https://github.com/hughjonesd/huxtable/assets/567550/872ac2dd-7b2b-44bb-b0da-c3e4e80a4c5f)

so that the background hides or erases the border.

### Without merge_cells
ok for line 1 but not the others

```
jams |> 
  insert_row(c("other", 12)) |>
  set_background_color(row = 1, col=2, value = "cornsilk1") |>
  set_background_color(row = 3, col=2, value = "cornsilk1") |>
  set_top_border(value = brdr(1), row = 1)|>
  set_top_border(value = brdr(.2), row = 2:3)|>
  set_bottom_border(value = brdr(.2), row = 1:3)|>
  set_bottom_border(value = brdr(1), row = final(1)) 

```

![Capture d’écran du 2023-12-14 13-00-48](https://github.com/hughjonesd/huxtable/assets/567550/2769766e-ee35-465e-bcd2-3d5db700ced6)

## other try

```
jams |> 
  set_background_color(row = 1:3, col=2, value = "cornsilk1") |>
  set_top_border(value = brdr(1), row = 1)|>
  set_top_border(value = brdr(.2), row = 2:3)|>
  set_bottom_border(value = brdr(.2), row = 1:3)|>
  set_bottom_border(value = brdr(1), row = final(1)) 

  
```

![Capture d’écran du 2023-12-14 13-02-45](https://github.com/hughjonesd/huxtable/assets/567550/3358d2a0-0cba-407b-8e19-1454ce1bea9a)

thanks, very nice package

**Comment by hughjonesd** [comment] 2023-12-15 07:48
What happens if you use thicker borders?

**Comment by hughjonesd** [comment] 2023-12-15 07:55
Cannot reproduce on my machine:

```r
jams |> 
  insert_row(c("other", 12)) |>
  merge_cells(1, 1:2)|>
  set_background_color(row = 1, col=2, value = "cornsilk1") |>
  set_background_color(row = 3, col=2, value = "cornsilk1") |>
  set_top_border(value = brdr(1), row = 1)|>
  set_top_border(value = brdr(.2), row = 2:3)|>
  set_bottom_border(value = brdr(.2), row = 1:3)|>
  set_bottom_border(value = brdr(1), row = final(1)) |>
  quick_pdf()
```

<img width="477" alt="image" src="https://github.com/hughjonesd/huxtable/assets/5818871/a6f910f8-77e1-4a43-b6d5-759293960d53">

* What version of huxtable? 
* Have you tried a different PDF viewer? 
* How are you compiling the PDF?

**Comment by blset** [comment] 2023-12-15 08:41
I see all ok in whats generated by quick_pdf in your example
with my pdf viewer (okular or bare linux pdf viewer)

but same problem even with thicker borders using :

knitr 1.45
huxtable 5.5.3

and lualatex or xelatex 


tinytex::tlmgr_version()
tlmgr revision 63068 (2022-04-18 07:58:07 +0200)
tlmgr using installation: /home/blset/.TinyTeX
TeX Live (https://tug.org/texlive) version 2022


the pdf that gets generated 
[testhux.pdf](https://github.com/hughjonesd/huxtable/files/13682886/testhux.pdf)

BUT
looks different when seen on my machine and when seen on the navigator (by visiting the link above)
it looks almost ok when seen on the navigator, but not perfect, and borders disappearing on my machine

but how come running though quick_pdf gives a perfect result, when seen with the same pdf viewer on the same machine ?






testhux.R
```

library(knitr)
library(huxtable)
knit2pdf(
     "testhux.Rnw",
     output = "testhux.tex",
     compiler ="xelatex"
)

```
testhux.Rnw

```


\documentclass[BCOR=2mm, DIV=6, twoside]{scrbook}

\KOMAoptions{fontsize=12, draft=true, chapterprefix=false, open=right}

\usepackage{fontspec}

\usepackage[left=2.5cm,right=2.5cm,top=3cm,bottom=3cm]{geometry}


% huxtable specific
\usepackage{array}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{siunitx}
\usepackage[normalem]{ulem}
\usepackage{colortbl}
\usepackage{multirow}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{threeparttable}
\usepackage{wrapfig}
\usepackage{adjustbox}
\usepackage{hyperref}
\begin{document}

<<>>=

jams |> 
    insert_row(c("other", 12)) |>
    merge_cells(1, 1:2)|>
    set_background_color(row = 1, col=2, value = "cornsilk1") |>
    set_background_color(row = 3, col=2, value = "cornsilk1") |>
    set_top_border(value = brdr(1), row = 1)|>
    set_top_border(value = brdr(.2), row = 2:3)|>
    set_bottom_border(value = brdr(.2), row = 1:3)|>
    set_bottom_border(value = brdr(1), row = final(1))


@


<<>>=

jams |> 
    insert_row(c("other", 12)) |>
    merge_cells(1, 1:2)|>
    set_background_color(row = 1:3, col=2, value = "cornsilk1") |>
    set_top_border(value = brdr(1), row = 1)|>
    set_top_border(value = brdr(.2), row = 2:3)|>
    set_bottom_border(value = brdr(.2), row = 1:3)|>
    set_bottom_border(value = brdr(1), row = final(1))


@
\end{document}

```

generated latex

```


\documentclass[BCOR=2mm, DIV=6, twoside]{scrbook}\usepackage[]{graphicx}\usepackage[]{xcolor}
% maxwidth is the original width if it is less than linewidth
% otherwise use linewidth (to make sure the graphics do not exceed the margin)
\makeatletter
\def\maxwidth{ %
  \ifdim\Gin@nat@width>\linewidth
    \linewidth
  \else
    \Gin@nat@width
  \fi
}
\makeatother

\definecolor{fgcolor}{rgb}{0.345, 0.345, 0.345}
\newcommand{\hlnum}[1]{\textcolor[rgb]{0.686,0.059,0.569}{#1}}%
\newcommand{\hlstr}[1]{\textcolor[rgb]{0.192,0.494,0.8}{#1}}%
\newcommand{\hlcom}[1]{\textcolor[rgb]{0.678,0.584,0.686}{\textit{#1}}}%
\newcommand{\hlopt}[1]{\textcolor[rgb]{0,0,0}{#1}}%
\newcommand{\hlstd}[1]{\textcolor[rgb]{0.345,0.345,0.345}{#1}}%
\newcommand{\hlkwa}[1]{\textcolor[rgb]{0.161,0.373,0.58}{\textbf{#1}}}%
\newcommand{\hlkwb}[1]{\textcolor[rgb]{0.69,0.353,0.396}{#1}}%
\newcommand{\hlkwc}[1]{\textcolor[rgb]{0.333,0.667,0.333}{#1}}%
\newcommand{\hlkwd}[1]{\textcolor[rgb]{0.737,0.353,0.396}{\textbf{#1}}}%
\let\hlipl\hlkwb

\usepackage{framed}
\makeatletter
\newenvironment{kframe}{%
 \def\at@end@of@kframe{}%
 \ifinner\ifhmode%
  \def\at@end@of@kframe{\end{minipage}}%
  \begin{minipage}{\columnwidth}%
 \fi\fi%
 \def\FrameCommand##1{\hskip\@totalleftmargin \hskip-\fboxsep
 \colorbox{shadecolor}{##1}\hskip-\fboxsep
     % There is no \\@totalrightmargin, so:
     \hskip-\linewidth \hskip-\@totalleftmargin \hskip\columnwidth}%
 \MakeFramed {\advance\hsize-\width
   \@totalleftmargin\z@ \linewidth\hsize
   \@setminipage}}%
 {\par\unskip\endMakeFramed%
 \at@end@of@kframe}
\makeatother

\definecolor{shadecolor}{rgb}{.97, .97, .97}
\definecolor{messagecolor}{rgb}{0, 0, 0}
\definecolor{warningcolor}{rgb}{1, 0, 1}
\definecolor{errorcolor}{rgb}{1, 0, 0}
\newenvironment{knitrout}{}{} % an empty environment to be redefined in TeX

\usepackage{alltt}

\KOMAoptions{fontsize=12, draft=true, chapterprefix=false, open=right}

\usepackage{fontspec}

\usepackage[left=2.5cm,right=2.5cm,top=3cm,bottom=3cm]{geometry}


% huxtable specific
\usepackage{array}
\usepackage{caption}
\usepackage{graphicx}
\usepackage{siunitx}
\usepackage[normalem]{ulem}
\usepackage{colortbl}
\usepackage{multirow}
\usepackage{hhline}
\usepackage{calc}
\usepackage{tabularx}
\usepackage{threeparttable}
\usepackage{wrapfig}
\usepackage{adjustbox}
\usepackage{hyperref}
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\begin{document}

\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{jams |>}
    \hlkwd{insert_row}\hlstd{(}\hlkwd{c}\hlstd{(}\hlstr{"other"}\hlstd{,} \hlnum{12}\hlstd{)) |>}
    \hlkwd{merge_cells}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{1}\hlopt{:}\hlnum{2}\hlstd{)|>}
    \hlkwd{set_background_color}\hlstd{(}\hlkwc{row} \hlstd{=} \hlnum{1}\hlstd{,} \hlkwc{col}\hlstd{=}\hlnum{2}\hlstd{,} \hlkwc{value} \hlstd{=} \hlstr{"cornsilk1"}\hlstd{) |>}
    \hlkwd{set_background_color}\hlstd{(}\hlkwc{row} \hlstd{=} \hlnum{3}\hlstd{,} \hlkwc{col}\hlstd{=}\hlnum{2}\hlstd{,} \hlkwc{value} \hlstd{=} \hlstr{"cornsilk1"}\hlstd{) |>}
    \hlkwd{set_top_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{1}\hlstd{),} \hlkwc{row} \hlstd{=} \hlnum{1}\hlstd{)|>}
    \hlkwd{set_top_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{.2}\hlstd{),} \hlkwc{row} \hlstd{=} \hlnum{2}\hlopt{:}\hlnum{3}\hlstd{)|>}
    \hlkwd{set_bottom_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{.2}\hlstd{),} \hlkwc{row} \hlstd{=} \hlnum{1}\hlopt{:}\hlnum{3}\hlstd{)|>}
    \hlkwd{set_bottom_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{1}\hlstd{),} \hlkwc{row} \hlstd{=} \hlkwd{final}\hlstd{(}\hlnum{1}\hlstd{))}
\end{alltt}
\end{kframe}
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{#1}\vrule width #2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{#1}}
  \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}

\begin{table}[ht]
\begin{centerbox}
\begin{threeparttable}
 \label{tab:unnamed-chunk-1}
\setlength{\tabcolsep}{0pt}
\begin{tabular}{l l}


\hhline{>{\huxb{0, 0, 0}{1}}->{\huxb{0, 0, 0}{1}}-}
\arrayrulecolor{black}

\multicolumn{2}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} other \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.2}}->{\huxb{0, 0, 0}{0.2}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Type \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} Price \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.2}}->{\huxb{0, 0, 0}{0.2}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Strawberry \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{255, 248, 220}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 1.90 \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.2}}->{\huxb{0, 0, 0}{0.2}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Raspberry \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 2.10 \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Plum \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 1.80 \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{1}}->{\huxb{0, 0, 0}{1}}-}
\arrayrulecolor{black}
\end{tabular}
\end{threeparttable}\par\end{centerbox}

\end{table}
\end{knitrout}


\begin{knitrout}
\definecolor{shadecolor}{rgb}{0.969, 0.969, 0.969}\color{fgcolor}\begin{kframe}
\begin{alltt}
\hlstd{jams |>}
    \hlkwd{insert_row}\hlstd{(}\hlkwd{c}\hlstd{(}\hlstr{"other"}\hlstd{,} \hlnum{12}\hlstd{)) |>}
    \hlkwd{merge_cells}\hlstd{(}\hlnum{1}\hlstd{,} \hlnum{1}\hlopt{:}\hlnum{2}\hlstd{)|>}
    \hlkwd{set_background_color}\hlstd{(}\hlkwc{row} \hlstd{=} \hlnum{1}\hlopt{:}\hlnum{3}\hlstd{,} \hlkwc{col}\hlstd{=}\hlnum{2}\hlstd{,} \hlkwc{value} \hlstd{=} \hlstr{"cornsilk1"}\hlstd{) |>}
    \hlkwd{set_top_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{1}\hlstd{),} \hlkwc{row} \hlstd{=} \hlnum{1}\hlstd{)|>}
    \hlkwd{set_top_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{.2}\hlstd{),} \hlkwc{row} \hlstd{=} \hlnum{2}\hlopt{:}\hlnum{3}\hlstd{)|>}
    \hlkwd{set_bottom_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{.2}\hlstd{),} \hlkwc{row} \hlstd{=} \hlnum{1}\hlopt{:}\hlnum{3}\hlstd{)|>}
    \hlkwd{set_bottom_border}\hlstd{(}\hlkwc{value} \hlstd{=} \hlkwd{brdr}\hlstd{(}\hlnum{1}\hlstd{),} \hlkwc{row} \hlstd{=} \hlkwd{final}\hlstd{(}\hlnum{1}\hlstd{))}
\end{alltt}
\end{kframe}
  \providecommand{\huxb}[2]{\arrayrulecolor[RGB]{#1}\global\arrayrulewidth=#2pt}
  \providecommand{\huxvb}[2]{\color[RGB]{#1}\vrule width #2pt}
  \providecommand{\huxtpad}[1]{\rule{0pt}{#1}}
  \providecommand{\huxbpad}[1]{\rule[-#1]{0pt}{#1}}

\begin{table}[ht]
\begin{centerbox}
\begin{threeparttable}
 \label{tab:unnamed-chunk-2}
\setlength{\tabcolsep}{0pt}
\begin{tabular}{l l}


\hhline{>{\huxb{0, 0, 0}{1}}->{\huxb{0, 0, 0}{1}}-}
\arrayrulecolor{black}

\multicolumn{2}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} other \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.2}}->{\huxb{0, 0, 0}{0.2}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Type \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{255, 248, 220}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} Price \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.2}}->{\huxb{0, 0, 0}{0.2}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Strawberry \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\cellcolor[RGB]{255, 248, 220}\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 1.90 \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{0.2}}->{\huxb{0, 0, 0}{0.2}}-}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Raspberry \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 2.10 \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{}
\arrayrulecolor{black}

\multicolumn{1}{!{\huxvb{0, 0, 0}{0}}l!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedright \hspace{6pt} Plum \hspace{6pt}\huxbpad{6pt}} &
\multicolumn{1}{r!{\huxvb{0, 0, 0}{0}}}{\huxtpad{6pt + 1em}\raggedleft \hspace{6pt} 1.80 \hspace{6pt}\huxbpad{6pt}} \tabularnewline[-0.5pt]


\hhline{>{\huxb{0, 0, 0}{1}}->{\huxb{0, 0, 0}{1}}-}
\arrayrulecolor{black}
\end{tabular}
\end{threeparttable}\par\end{centerbox}

\end{table}
\end{knitrout}
             \end{document}

```

**Comment by blset** [comment] 2023-12-15 08:52
when looking at the pdf on the navigator (visiting the link) 
looks like borders are here but the yellow square is shifted by some pth ixels

when viewing with okular , borders disappear
when viewing with evince 3.36.10 , it's all ok

when viewing the table generated by with quick_pdf, all ok with all pdf viewers

**Comment by hughjonesd** [comment] 2023-12-15 13:04
This also works fine on my machine, using `knitr::knit2pdf` and `xelatex`. I think it is probably just an issue with some pdf viewers that don't display very fine lines. Closing, but reopen if you think there is a huxtable issue. Thanks for the report.

**Closed by hughjonesd** 2023-12-15 13:04 UTC
