### ISSUE TITLE
Huxtable prints [ht] before the table in quarto pdf

### ISSUE THREAD

**Issue by ailich** [hughjonesd/huxtable#223] opened 2022-04-08 20:45 UTC
Hi, I started using huxtable and Quarto in Rstudio. It seems that huxtable mostly compatible with the new Quarto interface but for some reason there is an "[ht]" that gets rendered in front of the table when a caption is added. I modified the example [here](https://quarto.org/docs/authoring/tables.html) for creating a kable to make a huxtable with a label and caption. Below is an example of the code in the qmd file as well as a screenshot of how it renders.
~~~
---
title: "test"
format: pdf
editor: visual
---

```{r}
#| include: false
library(huxtable)
```

@tbl-iris shows up and can be cross-referenced, but it has an "\[ht\]" in front of it.

```{r}
#| label: tbl-iris
#| tbl-cap: "Iris Data"

hux(head(iris, n = 1))
```
~~~

![Screenshot 2022-04-08 164432](https://user-images.githubusercontent.com/28163862/162527530-fee3844a-7289-4a70-96b0-f455ac25dc3c.png)

**Comment by hughjonesd** [comment] 2022-04-08 21:08
Thanks for this. Can reproduce. Seems that quarto is interfering with table production: it takes
`\begin{table}[ht]` and inserts its caption before the `[ht]`.  Probably a quarto bug, because `[ht]` is part of the `\begin{table}` command.

Interestingly, if I create a caption of my own using `set_caption()`, that gets turned into a sub-caption.

**Comment by hughjonesd** [comment] 2022-04-08 21:12
OK, this requires a bunch of work to be compatible with quarto. A workaround for now is to set captions using ordinary huxtable means, e.g. `caption(ht) <- "My caption"`, not using chunk options. But, labels are still a problem.

**Comment by ailich** [comment] 2022-04-11 17:50
@hughjonesd, yeah I'm also noticing that if instead of using both the quarto labeling and caption syntax, I instead use both the huxtable `label` and `caption` functions, then caption gets set correctly , but the cross references break, but if I use the quarto labeling syntax and huxtable's `caption` function then it gets added as a sub-caption. Also thank you for reporting it to the Quarto devs and proposing a fix.

~~~
---
title: "test"
format: pdf
editor: visual
---

```{r}
#| include: false
library(huxtable)
```

@tbl-iris shows up but cannot be cross-referenced.

```{r}
mytab<- hux(head(iris, n = 1))
label(mytab)<- "tbl-iris"
caption(mytab)<- "My caption"
mytab
```
~~~



![Screenshot 2022-04-11 134726](https://user-images.githubusercontent.com/28163862/162799077-25d90b99-754c-4464-8f06-79dac72817eb.png)



~~~
---
title: "test"
format: pdf
editor: visual
---

```{r}
#| include: false
library(huxtable)
```

@tbl-iris shows up and can be cross-referenced, but the caption is a subcaption

```{r}
#| label: tbl-iris

mytab<- hux(head(iris, n = 1))
caption(mytab)<- "My caption"
mytab
```
~~~
![Screenshot 2022-04-11 134405](https://user-images.githubusercontent.com/28163862/162798628-f301c793-ec18-4f3d-9278-aee03a798dce.png)

**Comment by hughjonesd** [comment] 2022-04-12 13:48
If and when quarto gets updated with my PR, could you test?

**Comment by ailich** [comment] 2022-04-12 15:17
Sure thing. I'll keep an eye out to see if they add it.

**Comment by hughjonesd** [comment] 2022-04-15 13:54
Should be fixed in quarto master now, could you check?

**Comment by ailich** [comment] 2022-04-15 14:59
No more "[ht]" when using the development version of quarto!

**Comment by hughjonesd** [comment] 2022-04-15 15:51
Good news. Closing.

**Closed by hughjonesd** 2022-04-15 15:51 UTC
